build:
	g++ -std=c++11 lodepng.cpp Light.cpp Polygon.cpp SMFModel.cpp Sphere.cpp Model.cpp Ray.cpp Camera.cpp Vector3D.cpp Vector4D.cpp sak338_hw2.cpp -o sak338_hw2 -ansi -pedantic -Wall -Wextra -O3 -w

run: build 
	./sak338_hw2

clean:
	rm -f sak338_hw2
	rm -f *png
